Update docs
ROCm/rocWMMA pull request #379
Opened 2024-04-03 22:00 UTC by cgmillette

Updating documents from:
- What is rocWMMA
- Installation
- Programmers guide
- README.md

2024-04-10 19:57 UTC, samjwu commented
For some reason the updated RTD config that uses mambaforge with doxygen 1.9.8 fails to pull the API functions correctly

Setting WARN_IF_DOC_ERROR to NO will avoid the Doxygen warning when multiple params have the same name

2024-04-24 17:53 UTC, mkarunan commented on docs/programmers-guide.rst
> +  - Vector packing and unpacking
- data layout transformation utilities

2024-04-24 19:19 UTC, CongMa13 requested changes
The new document looks awesome! Especially the programmer's guide.

2024-04-24 19:19 UTC, CongMa13 commented on docs/installation.rst
> +The rocWMMA source code is available at the `rocWMMA github page <https://github.com/ROCmSoftwarePlatform/rocWMMA>`_. rocWMMA has a minimum ROCm support version 6.0.
This link is still alive. But wmma has moved to https://github.com/ROCm/rocWMMA

2024-04-24 19:19 UTC, CongMa13 commented on docs/installation.rst
> +
render result of these lines:
![image](https://github.com/ROCm/rocWMMA/assets/142121551/f1877c08-23d7-4560-80b4-e07fc19984cc)

expect a Note

![image](https://github.com/ROCm/rocWMMA/assets/142121551/033f87bf-4fed-42f0-a9ce-6e04269ce8f5)

2024-04-24 20:43 UTC, dlangbe commented on docs/api-reference-guide.rst
> +* bf16 = 8-bit precision brain floating point
bf8

2024-04-24 20:43 UTC, dlangbe commented on docs/installation.rst
> +Running the above commands generates ``rocwmma.pdf``.
Should these doc build instructions be identical in the README?

2024-04-24 20:43 UTC, dlangbe commented on docs/installation.rst
> +    cmake --build <build_dir> -- -j<nproc>
Duplicate cmake instruction as line 255. Should consider consolidating all cmake build instructions.

2024-04-24 20:43 UTC, dlangbe commented on docs/installation.rst
> +    cmake --build <build_dir> -- -j<nproc>
Same comment about consolidation.

2024-04-24 20:43 UTC, dlangbe commented on docs/programmers-guide.rst
> +The programming model that is the most useful with the rocWMMA API is wavefront-centric, in that all function calls will be assumed involve the entire wavefront. In a more general
*assumed to involve

2024-04-24 20:43 UTC, dlangbe commented on docs/programmers-guide.rst
> +Dependent Lookup (ADL) and other deduction techniques. Of major importance to rocWMMA, the user first configures the fragments correctly and rocWMMA conveniently takes
Reword "Of major importance..." to:
In practice, the user must simply configure the fragments correctly for their problem and rocWMMA conveniently takes care of the rest.

2024-04-24 20:43 UTC, dlangbe commented on docs/programmers-guide.rst
> +care of the rest. The rocWMMA API can eliminate a very large amount of boiler-plate code as it provides tools to decompose matrix multiply-accumulate based problems into
The last sentence seems out of place. It should be placed before the introduction of  what fragments are.

2024-04-24 20:43 UTC, dlangbe commented on docs/programmers-guide.rst
> +- Fragment operations. This is the API level of rocWMMA where user data is stored and manipulated in ``fragment`` objects. Fragment objects can be visualized as geometric 'blocks' of data in the pers
Reword "This way, the rocWMMA API..." to:
The encapsulation of rocWMMA into these separate layers allows for an API experience that is seamless across different device architectures and platforms.

2024-04-24 20:43 UTC, dlangbe commented on docs/programmers-guide.rst
> +  block of matrix multiplication per wave. No prefetch, no lDs usage, default MFMA prioritization, single
Should this and the following occurrences of "lDs" be capitalized like this?

2024-04-24 20:43 UTC, dlangbe commented on docs/what-is-rocwmma.rst
> +and compile-time inferences and optimizations. The API is seamless across supported CDNA and RDNA architectures. It is also portable with Nvidia
*portable with the...

2024-04-24 20:43 UTC, dlangbe commented on docs/what-is-rocwmma.rst
> +API functions consist data loading and storing, matrix multiply-accumulate and helper transforms operating on data fragment abstractions. Moreover, data movement
Consider changing to:
API functions include data loading and storing, matrix multiply-accumulate and helper transforms that operate on data fragment abstractions.

2024-04-24 20:43 UTC, dlangbe commented on library/include/rocwmma/rocwmma.hpp
> + * and optimizations. The API is seamless across supported CDNA and RDNA architectures. It is also portable with Nvidia nvcuda::wmma library, allowing those users to easily migrate
Consider the same requested changes as in what-is-rocwmma.rst

2024-04-24 22:38 UTC, cgmillette commented on docs/installation.rst
> +Running the above commands generates ``rocwmma.pdf``.
Added both html and pdf instructions to both areas

2024-04-24 22:42 UTC, cgmillette commented on docs/installation.rst
> +    cmake --build <build_dir> -- -j<nproc>
The initial cmake call is for the configuration

Subsequent calls to cmake --build are invoking the compiler, which should be now configured.

2024-04-24 23:17 UTC, cgmillette commented
Feedback has been incorporated

2024-04-25 13:35 UTC, mkarunan approved these changes
Looks great!

2024-04-26 15:27 UTC, CongMa13 approved these changes

2024-04-26 22:38 UTC, merged